project:
  type: website
  output-dir: docs

website:
  title: "Curso Finanzas en R"
  navbar:
    left:
      - text: "Inicio"
        href: index.qmd
      - text: "Clases"
        href: clases.qmd
      - text: "Recursos"
        href: recursos.qmd
      - text: "Contacto"
        href: contacto.qmd

format:
  html:
    theme: cosmo
    toc: true


